#!/bin/sh -ex

# 
# Install odoo deps - Start of 10_depedencies 
#  
 
# Install gdata 2.0.17
# Should use ver= as below for gdata
# 
VER=2.0.17
cd /opt/openerp
wget http://gdata-python-client.googlecode.com/files/gdata-${VER}.tar.gz
tar -zxvf gdata-${VER}.tar.gz
cd gdata-2.0.17
python setup.py install
cd ..


# Intall wkhtmltox 0.12.2.1 - Used for HTML to PDF for reports 
#
ARCH=amd64
REL=jessie
GEN=0.12
VER=0.12.2.1
wget http://download.gna.org/project/wkhtmltopdf/${GEN}/wkhtmltox-${VER}_linux-${REL}-${ARCH}.deb
dpkg -i wkhtmltox-*.deb

# wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb
# dpkg -i wkhtmltox-0.12.2.1_linux-jessie-amd64.deb
cp /usr/local/bin/wkhtmltopdf /usr/bin
cp /usr/local/bin/wkhtmltoimage /usr/bin

# 
# Install odoo deps - End of 10_depedencies
# 
