#!/bin/sh -ex

GDATA_VER = 2.0.17
WKHTMLTOX_VER = 0.12.2.1

cd /opt/openerp
wget http://gdata-python-client.googlecode.com/files/gdata-${GDATA_VER}.tar.gz
tar -zxvf gdata-${GDATA_VER}.tar.gz
chown -R openerp:openerp gdata-${GDATA_VER}
cd gdata-#{GDATA_VER}
python setup.py install

cd /

mkdir /opt/wkhtmltopdf/wkhtmltox
mkdir /opt/wkhtmltopdf/wkhtmltox
wget http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-${WKHTMLTOX_VER}_linux-${REL}-${ARCH}.deb 
dpkg -i wkhtmltox-${WKHTMLTOX_VER}_linux-${REL}-${ARCH}.deb

cp /usr/local/bin/wkhtmltopdf /usr/bin
cp /usr/local/bin/wkhtmltoimage /usr/bin
