#!/bin/sh -ex

cd /opt/openerp
wget http://gdata-python-client.googlecode.com/files/gdata-2.0.17.tar.gz
tar -zxvf gdata-2.0.17.tar.gz

cd gdata-2.0.17
python setup.py install
cd ..


wget http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb 
dpkg -i wkhtmltox-0.12.2.1_linux-jessie-amd64.deb

cp /usr/local/bin/wkhtmltopdf /usr/bin
cp /usr/local/bin/wkhtmltoimage /usr/bin
