#!/bin/sh -ex

#
# START - Install Odoo - 30_main
#
 
# Set variables
# 
DB_USER=openerp
DB_PASS=$(mcookie)

# We will use a random password for now. Set it during inithook
ODOO_ADMIN_PASSWORD=$(mcookie)

# User name that Odoo will run under
SERVICE_USER=$DB_USER

OPENERP_DIR=/opt/openerp
ODOO_DIR=$OPENERP_DIR/odoo
CONF=/etc/odoo/openerp-server.conf

# Create database role for odoo
# 

# Start postgresql server
/etc/init.d/postgresql start

# Create db user
su postgres -c "createuser --superuser --createdb --no-createrole $DB_USER"

# Set db user password
su postgres -c "psql postgres" << EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF

# Set password in config file
sed -i "s|db_password =.*|db_password = $DB_PASS|" $CONF

# Stop postgresql server
/etc/init.d/postgresql stop
#

# Add service account user
#

# Add user without home dir
useradd -M $SERVICE_USER 

# Set shell
usermod -s /bin/bash $SERVICE_USER

# Disable user
usermod -L $SERVICE_USER 


# Install Odoo
# 

git clone https://github.com/odoo/odoo.git --branch 8.0 --depth=1 $ODOO_DIR

# Set admin password to random value for now
sed -i "s|admin_passwd =.*|admin_passwd = $ODOO_ADMIN_PASSWORD|" $CONF

# Create lib
mkdir /var/lib/odoo
chown -R openerp:openerp /var/lib/odoo 

# Install Odoo as a service
# 

update-rc.d openerp-server defaults

# Symlinks attemps commented 73-77 and 85-92
# cd /opt/openerp		
# ln -s openerp.init /etc/init.d/openerp-server
# touch openerp.init
# chown openerp openerp.init

# Change Ownership Landis
touch /etc/odoo/openerp-server.conf
chown openerp /etc/odoo/openerp-server.conf
touch /etc/init.d/openerp-server
chown openerp /etc/init.d/openerp-server

touch /var/log/openerp-server.log
chown openerp /var/log/openerp-server.log
touch /var/run/openerp-server.pid
chown openerp /var/run/openerp-server.pid
chown -R openerp:openerp $ODOO_DIR

# make softlink for openerp.server.conf
# cd $OPENERP_DIR/odoo
# ln -s openerp-server.conf /etc/odoo/openerp-server.conf
# touch openerp-server.conf
# chown openerp openerp-server.conf
# cd /etc/odoo
# touch openerp-server.conf
# chown openerp openerp-server.conf

# Perform apache config		
# Enable needed modules
# 
a2enmod ssl proxy_http headers rewrite		

# Enable sites
a2ensite openerp-ssl.conf		
a2ensite odoo-80.conf		
# WebConsole is disabled but available by typing the following line in shell
a2ensite odoo-12325.conf		

# odoo-12325.conf also creates port 12324 for SSL		
# Port 12324 for SSL

