#!/bin/sh -ex

#
# START - Install Odoo - 30_main
#
 
# Set variables
# 
DB_USER=openuser
DB_PASS=$(mcookie)

# We will use a random password for now. Set it during inithook
ODOO_ADMIN_PASSWORD=$(mcookie)

# User name that Odoo will run under
SERVICE_USER=openerp

OPENERP_DIR=/opt/openerp
ODOO_DIR=$OPENERP_DIR/odoo
SERVER_CONF=$ODOO_DIR/openerp-server.conf

# Create database role for odoo
# 

# Start postgresql server
/etc/init.d/postgresql start

# Create db user
su postgres -c "createuser --superuser --createdb --no-createrole $DB_USER"

# Set db user password
su postgres -c "psql postgres" << EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF

# Set password in config file
sed -i "s|db_password =.*|db_password = $DB_PASS|" $SERVER_CONF

# Stop postgresql server
/etc/init.d/postgresql stop
# 



# Add service account user
#

# Add user without home dir
useradd -M $SERVICE_USER 

# Set shell
usermod -s /bin/bash $SERVICE_USER

# Disable user
usermod -L $SERVICE_USER 


# Install Odoo
# 

# Since we have config files in the overlay, this creates the install dir
#   Because this already exists, git-clone will yell at us. So clone to temp
#   then we can move the files back to where we want them and not over write
#   out config files we have updated

git clone https://github.com/odoo/odoo.git --branch 8.0 --depth=1  /tmp/odoo_temp

# We could remove the git repo, would make updates harder.
# rm -rt  /tmp/odoo_temp/.git

# Move the files, but don't change existing ones 
mv -n -t $ODOO_DIR /tmp/odoo_temp/*
rm -rf /tmp/odoo_tmp

# Set admin password to random value for now
sed -i "s|admin_passwd =.*|admin_passwd = $ODOO_ADMIN_PASSWORD|" $SERVER_CONF

# Give ownership to openerp user
chown -R openerp:openerp $ODOO_DIR
# 

# Create lib
mkdir /var/lib/odoo
chown -R openerp:openerp /var/lib/odoo 

# Install Odoo as a service
# 

chmod 666 /opt/openerp/openerp.init 
chmod +x /opt/openerp/openerp.init
cd /etc/init.d
ln -s $OPENERP_DIR/openerp.init openerp-server
update-rc.d openerp-server defaults
touch /var/log/openerp-server.log
chown openerp /var/log/openerp-server.log
touch /var/run/openerp-server.pid
chown openerp /var/run/openerp-server.pid
chown -R openerp:openerp $ODOO_DIR
# 

# make softlink for openerp.server.conf
cd /etc/odoo
ln -s $OPENERP_DIR/odoo/openerp-server.conf openerp-server.conf
touch openerp-server.conf
chown openerp openerp-server.conf
cd $OPENERP_DIR/odoo/openerp-server.conf
touch openerp-server.conf
chown openerp openerp-server.conf

# Perform apache config		
# Enable needed modules
# 
a2enmod ssl proxy_http headers rewrite		

# Enable sites
a2ensite openerp-ssl.conf		
a2ensite odoo-80.conf		
# WebConsole is disabled but available by typing the following line in shell
a2ensite odoo-12325.conf		

# odoo-12325.conf also creates port 12324 for SSL		
# Port 12324 for SSL

