#!/bin/sh -ex

OPENERP_PASS=openerp
OPENERP_DIR=/opt/openerp
ODOO_DIR=/opt/openerp/odoo
ODOO_DIR_TMP=/opt/openerp/odoo_tmp

echo "------------------------"
echo " Create a role openuser "
echo "------------------------"
/etc/init.d/postgresql start
su -c - postgres "createuser openuser --no-superuser --createdb --no-createrole" 
cat > /tmp/openuser_changepass.sql <<"EOF"
ALTER USER openuser WITH PASSWORD 'openuser';
EOF
su -c - postgres "psql template1 -U postgres -f /tmp/openuser_changepass.sql"
/etc/init.d/postgresql stop

echo "-------------------------"
echo " Add system user openerp "
echo "-------------------------"
echo | adduser --disabled-password openerp
usermod -p $(echo $OPENERP_PASS | openssl passwd -1 -stdin) openerp

echo "--------------------------"
echo " Create openerp directory "
echo "--------------------------"
#mkdir $OPENERP_DIR
chown -R openerp:openerp $OPENERP_DIR

echo "--------------"
echo " Install Odoo "
echo "--------------"
git clone https://github.com/odoo/odoo.git $ODOO_DIR
chown -R openerp:openerp $ODOO_DIR
mv $ODOO_DIR_TMP/* $ODOO_DIR
rm -rf $ODOO_DIR_TMP

echo "----------------------------"
echo "  Install Odoo as a service "
echo "----------------------------"
chmod 666 /opt/openerp/openerp.init 
chmod +x /opt/openerp/openerp.init
cd /etc/init.d
ln -s $OPENERP_DIR/openerp.init openerp-server
update-rc.d openerp-server defaults
touch /var/log/openerp-server.log
chown openerp /var/log/openerp-server.log
touch /var/run/openerp-server.pid
chown openerp /var/run/openerp-server.pid
chown -R openerp:openerp $ODOO_DIR

echo "------------------------"
echo " Make SSL work properly "
echo "------------------------"
a2enmod ssl proxy_http headers rewrite
a2ensite openerp-ssl
