#!/bin/sh -ex

CLVSOL_ODOO_ADDONS_DIR=/opt/openerp/clvsol_odoo_addons
CLVSOL_ODOO_SOLUTIONS_DIR=/opt/openerp/clvsol_odoo_solutions

echo "----------------------------"
echo " Install CLVsol Odoo Addons "
echo "----------------------------"
git clone https://github.com/CLVsol/odoo_addons.git $CLVSOL_ODOO_ADDONS_DIR
chown -R openerp:openerp $CLVSOL_ODOO_ADDONS_DIR

echo "-------------------------------"
echo " Install CLVsol Odoo Solutions "
echo "-------------------------------"
git clone https://github.com/CLVsol/odoo_solutions.git $CLVSOL_ODOO_SOLUTIONS_DIR
chown -R openerp:openerp $CLVSOL_ODOO_SOLUTIONS_DIR
