#!/bin/sh -ex

echo "--------------------------"
echo " Install OCA Server Tools "
echo "--------------------------"
OCA_SERVER_TOOLS_DIR=/opt/openerp/oca/oca_server_tools
git clone https://github.com/OCA/server-tools.git --depth=1 $OCA_SERVER_TOOLS_DIR --branch 8.0  
chown -R openerp:openerp $OCA_SERVER_TOOLS_DIR


echo "--------------------------"
echo " Install Odoo Connector "
CONNECTOR_DIR=/opt/openerp/oca/connector
mkdir $CONNECTOR_DIR
git clone https://github.com/OCA/connector.git --depth=1 $CONNECTOR_DIR -b 8.0
chown -R openerp:openerp $CONNECTOR_DIR
echo " "

echo " Install Connector - Ecommerce"
CONNECTOR_ECOM_DIR=/opt/openerp/oca/connector-ecommerce
mkdir $CONNECTOR_ECOM_DIR
git clone https://github.com/OCA/connector-ecommerce.git --depth=1 $CONNECTOR_ECOM_DIR -b 8.0
chown -R openerp:openerp $CONNECTOR_ECOM_DIR
echo " "

echo " Install Connector - Magento"
CONNECTOR_MAGENTO_DIR=/opt/openerp/oca/connector-magento
mkdir $CONNECTOR_MAGENTO_DIR
git clone https://github.com/OCA/connector-magento.git --depth=1 $CONNECTOR_MAGENTO_DIR -b 8.0
chown -R openerp:openerp $CONNECTOR_MAGENTO_DIR
echo " "

echo " Install- Ecommerce GIT 2"
E_COMMERCE_DIR=/opt/openerp/oca/e-commerce
mkdir $E_COMMERCE_DIR
git clone https://github.com/OCA/e-commerce.git --depth=1 $E_COMMERCE_DIR -b 8.0
chown -R openerp:openerp $E_COMMERCE_DIR
echo " "

echo " Install Product Attributes"
PRODUCT_ATTRIBUTE_DIR=/opt/openerp/oca/product-attribute
mkdir $PRODUCT_ATTRIBUTE_DIR
git clone https://github.com/OCA/product-attribute.git --depth=1 $PRODUCT_ATTRIBUTE_DIR -b 8.0
chown -R openerp:openerp $PRODUCT_ATTRIBUTE_DIR
echo " "

echo " Install Sale - Workflow"
SALE_WORKFLOW_DIR=/opt/openerp/oca/sale-workflow
mkdir $SALE_WORKFLOW_DIR
git clone https://github.com/OCA/sale-workflow.git --depth=1 $SALE_WORKFLOW_DIR -b 8.0
chown -R openerp:openerp $SALE_WORKFLOW_DIR
echo " "
echo "--------------------------"

echo " Install Magento API"
MAGENTO_API_DIR=/opt/openerp/oca/openlabs-magento
mkdir $MAGENTO_API_DIR
git clone https://github.com/openlabs/magento --depth=1 $MAGENTO_API_DIR 
chown -R openerp:openerp $MAGENTO_API_DIR
cd $MAGENTO_API_DIR
python setup.py install
cd /
echo " Finished Install Magento API"
echo " "

echo "--------------------------"

