#!/bin/sh -ex

# Set variables
#
 
DB_USER=openerp
DB_PASS=$(mcookie)

# We will use a random password for now. Set it during inithook
ODOO_ADMIN_PASSWORD=$(mcookie)

# User name that Odoo will run under
SERVICE_USER=$DB_USER

OPENERP_DIR=/opt/openerp
ODOO_DIR=$OPENERP_DIR/odoo
CONF=/etc/odoo/openerp-server.conf


# Create database role for odoo
# *******************************************
 
# Start postgresql server
/etc/init.d/postgresql start

# Create db user
su postgres -c "createuser --superuser --createdb --no-createrole $DB_USER"

# Set db user password
su postgres -c "psql postgres" << EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF

# Set password in config file
sed -i "s|db_password =.*|db_password = $DB_PASS|" $CONF

# Stop postgresql server
/etc/init.d/postgresql stop


# Install Odoo from GIT repo
# *******************************************
git clone http://github.com/odoo/odoo.git --branch 8.0 --depth=1 $ODOO_DIR

# Set admin password to random value for now
sed -i "s|admin_passwd =.*|admin_passwd = $ODOO_ADMIN_PASSWORD|" $CONF



# Install Odoo as a service
# *******************************************

# Add service user and disable it
useradd -c "Odoo Service Account" -d "$OPENERP_DIR" -r -s "/bin/bash" $SERVICE_USER
usermod -L $SERVICE_USER

# Add service to startup
update-rc.d openerp-server defaults

# Change ownership for Odoo config file
chown $SERVICE_USER /etc/odoo/openerp-server.conf

# Create /var/lib/odoo
mkdir /var/lib/odoo
chown -R $SERVICE_USER:$SERVICE_USER /var/lib/odoo

# Create log file
touch /var/log/openerp-server.log
chown $SERVICE_USER /var/log/openerp-server.log

# Create PID file
touch /var/run/openerp-server.pid

# Set Odoo app directory owner
chown -R $SERVICE_USER:$SERVICE_USER $OPENERP_DIR





# Perform apache config		
#

# Enable needed modules
a2enmod ssl proxy_http headers rewrite		

# Enable sites
a2ensite openerp-ssl.conf		
a2ensite odoo-80.conf		

