#!/bin/bash -ex

# Set variables
#
 
DB_USER=odoo
DB_PASS=$(mcookie)
DB_NAME=odoo

# We will use a random password for now. Set it during inithook
ODOO_ADMIN_PASSWORD=$(mcookie)

# User name that Odoo will run under
SERVICE_USER=$DB_USER

ODOO_DIR=$OPENERP_DIR/odoo
CONF=/etc/odoo/odoo.conf

# Install odoo from third party repo
apt-get update
apt-get install -y odoo


# Install deps that can't be installed via package using pip
# *******************************************
pip3 install psycogreen


# Create database role for odoo
# *******************************************
 
# Start postgresql server
/etc/init.d/postgresql start

# Create db user
su postgres -c "createuser --superuser --createdb --no-createrole $DB_USER"

# Set db user password
su postgres -c "psql postgres" << EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF
su postgres -c "psql postgres" << EOF
create database $DB_NAME owner $DB_USER;
EOF

# Set password/name in config file
sed -i "s|db_password =.*|db_password = $DB_PASS|" $CONF
sed -i "s|db_name =.*|db_name = $DB_NAME|" $CONF

# Stop postgresql server
/etc/init.d/postgresql stop

# Set admin password to random value for now
sed -i "s|admin_passwd =.*|admin_passwd = $ODOO_ADMIN_PASSWORD|" $CONF

# Install Odoo as a service
# *******************************************

# Add and disable service user
usermod -L $SERVICE_USER

# Add service to startup
update-rc.d odoo defaults

# Enable needed modules
a2enmod proxy_http headers rewrite		

# Configure sites
a2dissite 000-default
a2ensite odoo.conf


# Populate database
service postgresql start
service apache2 start
service odoo start

while [[ "$(curl -Lk http://localhost)" = *"Unavailable"* ]]; do
    sleep 1
done

service postgresql stop
service apache2 stop
service odoo stop
