#!/bin/bash -e
# regenerate odoo pgsql password

. /etc/default/inithooks

CONF=/etc/odoo/openerp-server.conf
DB_USER=openerp

# Create new password
DB_PASS=$(mcookie)

# Set new password in config file
sed -i "s|db_password =.*|db_password = $DB_PASS|" $CONF

# Update the pastgres user password
$INITHOOKS_PATH/bin/pgsqlconf.py --user=$DB_USER --pass="$DB_PASS"

# Since we reset the password, reload Odoo
# Don't use systemd/systemctl right now as lxc/ovz does not
# use systemd
service openerp-server restart
