#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo/openerp-server.conf

PASSWORD=$(mcookie)
# sed -i "s/#db_password = openuser / db_password = ${PASSWORD}" $CONF

$INITHOOKS_PATH/bin/openuser.py --user=openuser --pass="PASSWORD"
