#!/bin/bash -e		
# set Odoo Admin password

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

$INITHOOKS_PATH/bin/odoo.py --pass="$APP_PASS"

# Since we reset the password, reload Odoo
# Don't use systemd/systemctl right now as lxc/ovz does not
# use systemd
service openerp-server restart
