#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo_tmp/openerp-server.conf

sed -i "s|db_password.*|db_password = '$PASSWORD';|" $CONF		
$INITHOOKS_PATH/bin/openuser.py --user=openuser --pass="$PASSWORD"

CONF=/opt/openerp/odoo/openerp-server-man.conf
sed -i "s|db_password.*|db_password = '$PASSWORD';|" $CONF
