#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo/openerp-server.conf

$INITHOOKS_PATH/bin/pgsqlconf.py --user=openuser --pass="$PASSWORD"
sed -i "s|db_password.*|db_password = '$PASSWORD';|" $CONF
