#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo_tmp/openerp-server.conf

DBPASS=$(mcookie)
sed -i "s|db_password.*|db_password = '$DBPASS';|" $CONF		
$INITHOOKS_PATH/bin/openuser.py --user=openuser --pass="$DBPASS"
