#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo/openerp-server.conf

PASSWORD=$(mcookie)
# sed -i "s/#db_password = openuser / db_password = ${PASSWORD}" $CONF

SITESALT=$(mcookie)$(mcookie)
sed -i "s|db_password =.*|db_password = '$SITESALT';|" $CONF

PASSWORD=$(mcookie)
sed -i "s|dbpass.*|dbpass = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/pgsqlconf.py --user=openuser --pass="$PASSWORD"
