#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo/openerp-server.conf

# PASSWORD=$(mcookie)
# SITESALT=$(mcookie)$(mcookie)
# sed -i "s|db_password =.*|db_password = '$SITESALT';|" $CONF

PASSWORD=$(mcookie)
$INITHOOKS_PATH/bin/openuser.py --user=openuser --pass="$PASSWORD"
sed -i "s|db_password.*|db_password = $PASSWORD|" $CONF
