#!/bin/bash -e		
# set Odoo Admin password

SERVER_CONF=/opt/openerp/odoo/openerp-server.conf

. /etc/default/inithooks
[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# Sets the admin password, if password is already set (pre-seeding)
# then does nothing, since all we are doing is grabbing from 
# console and setting variable
$INITHOOKS_PATH/bin/odoo.py --pass="$ODOO_ADMIN_PASS"

# Change the password now that we got it from the user or pre-seed
sed -i "s|admin_passwd.*|admin_passwd = $ODOO_ADMIN_PASS|" $SERVER_CONF
