#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo/openerp-server.conf

ODOO_DB_PASS=$(mcookie)
sed -i "s/#db_password = openuser / db_password = ${ODOO_DB_PASS}" $CONF

$INITHOOKS_PATH/bin/pgsqlconf.py --user=openuser --pass="ODOO_DB_PASS"
