#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo/openerp-server.conf

OPENPASS=$(mcookie)
sed -i "s/#db_password = openuser / db_password = ${OPENPASS}" $CONF

$INITHOOKS_PATH/bin/pgsqlconf.py --user=openuser --pass="OPENPASS"
