#!/bin/bash -e
# regenerate odoo site salt and pgsql password

. /etc/default/inithooks

CONF=/opt/openerp/odoo/openerp-server.conf

SITESALT=$(mcookie)$(mcookie)
sed -i "s|passwordsaltmain.*|passwordsaltmain = '$SITESALT';|" $CONF

PASSWORD=$(mcookie)
sed -i "s/#db_password = openuser / db_password = ${OPENERP_PASS}" $CONF

$INITHOOKS_PATH/bin/pgsqlconf.py --user=openuser --pass="$OPENERP_PASS"
