#!/bin/bash -e		
# set Odoo Admin password

 . /etc/default/inithooks
 
[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

ADMINPW=""
$INITHOOKS_PATH/bin/odoo.py --pass="ADMINPW"

CONF=/opt/openerp/odoo/openerp-server.conf
sed -i "s|admin_passwd.*|admin_passwd = ${ADMINPW}" $CONF  

