#!/bin/bash -e
# set odoo-db-pass aka ODOO_PASS password

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/odoo.py odoo-db-pass  --pass="$ODOO_PASS"

-----------
From Tendenci:
  #!/bin/bash -e
# set tendenci admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/tendenci.py --pass="$APP_PASS" --email="$APP_EMAIL"
