#!/bin/sh

### BEGIN INIT INFO
# Provides:		openerp-server
# Required-Start:	$remote_fs $syslog postgresql apache2
# Required-Stop:	$remote_fs $syslog postgresql apache2
# Should-Start:		$network
# Should-Stop:		$network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Open Enterprise Resource Management software
# Description:		Odoo is a complete ERP and CRM software.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/openerp/odoo/openerp-server
NAME=openerp-server
DESC=openerp-server
CONFIG=/etc/odoo/openerp-server.conf
DAEMON_LOGFILE=/var/log/odoo/openerp-server-startup.log
USER=openerp

test -x ${DAEMON} || exit 0

set -e

case "${1}" in
	start)
		echo -n "Starting ${DESC}: "
                echo "`date` - Starting ${DESC}: " >> ${DAEMON_LOGFILE}
                start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
                        --chuid ${USER} --background --no-close \
                        --exec ${DAEMON} -- --config=${CONFIG} >> ${DAEMON_LOGFILE} 2>&1

		echo "${NAME}."
		;;

	stop)
		echo -n "Stopping ${DESC}: "

		start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
			--oknodo
		echo "`date` - Stopping ${DESC}: " >> ${DAEMON_LOGFILE}
		echo "${NAME}."
		;;

	restart|force-reload)
		echo -n "Restarting ${DESC}: "
                echo "`date` - Restarting ${DESC}: " >> ${DAEMON_LOGFILE}
                echo "`date` - Stopping ${DESC}: " >> ${DAEMON_LOGFILE}
                start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
                        --oknodo

		sleep 15

                echo "`date` - Starting ${DESC}: " >> ${DAEMON_LOGFILE}
                start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
                        --chuid ${USER} --background --no-close \
                        --exec ${DAEMON} -- --config=${CONFIG}  >> ${DAEMON_LOGFILE} 2>&1

		echo "${NAME}."
		;;

	*)
		N=/etc/init.d/${NAME}
		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
